### ISSUE TITLE
pubg mobile support

### ISSUE THREAD

**Issue by Rithmatist** [zeroKilo/PUBGLiteExplorerWV#2]
Hello,

Great project you have made,

Can you also make it support pubg mobile .pak files?

Cheers

**Comment by zeroKilo** [comment]
Hello,
I think all you need to do is to the replace the encryption key with the one from mobile version, then this should already work for mobile. If you still have problems, pls contact me over discord :)
Have a nice day

**Comment by Rithmatist** [comment]
> Hello, I think all you need to do is to the replace the encryption key with the one from mobile version, then this should already work for mobile. If you still have problems, pls contact me over discord :) Have a nice day

your discord ign is zeroKilo ?

**Comment by zeroKilo** [comment]
https://discord.gg/VvpVv7gq im just wv there

**Comment by nitinrajg** [comment]
It's showing link expired
How  can I contact you

I need a pak tool
I have encryption key

**Comment by zeroKilo** [comment]
https://discord.gg/EsGP7ds6fH
